### ISSUE TITLE
Status "Updating"

### ISSUE THREAD

**Issue by coryabooth** [evantobin/homebridge-voiceiq#1]
Thanks for the work on this.

I added my VoiceIQ legacy (no Q-Code) device.
Obtained the Authorization Token (I had to use developer tools)
Set the plugin to Bridge Mode
Added device successfully

Faucet turns on and off in the large "switch view"

![1](https://user-images.githubusercontent.com/5266177/213201986-5d12b504-05c4-4c6c-b3db-6c40fa760c27.jpg)

But it does not respond to a press in the "icon" view and the status is consistently "Updating"

![2](https://user-images.githubusercontent.com/5266177/213202025-fd893d97-9e69-4533-bf56-07fde254e92b.jpg)

**Comment by PhiltorX** [comment]
Me too.

**Comment by coryabooth** [comment]
Actually I noticed this is mentioned in the description of the plug-in.

**Comment by justinshuls** [comment]
Same issue. Looks like it may have been fixed but plugin show 1.0 version via Hoobs. Perhaps needs to be updated on NPM?

**Comment by evantobin** [comment]
I think it's an iOS issue, because I didn't correct the code? I can update NPM with latest version, but the status will always be synthetic. Delta doesn't give an API to check the status. Any preferences as to how I should do it? Synthetic status (that ignores if the device is touched) or leaving it always off?

**Comment by justinshuls** [comment]
Actually crashes home app for me. maybe it can be changed to a momentary button if it has no status

**Comment by coryabooth** [comment]
Same for me.  App crashes when clicking "turn on"

**Comment by evantobin** [comment]
Version 1.0.1 has been released that switches the device type to a switch the avoid the issues with the faucet device type in homekit

**Comment by coryabooth** [comment]
I still see the same issue and attempting to control the faucet - the app crashes.  I'll try removing the cache and see if there is a change.

**Comment by evantobin** [comment]
@coryabooth I had to remove and readd homebridge to my home for it to see the new device type. You shouldn't see a faucet or water icon at all. If you are, the device is still being cached someplace.

**Comment by coryabooth** [comment]
Yep, that's all I needed to do...
Navigate to Settings, Remove Single Cached Accessory, Reboot...
You'll need to redo the API Key...
Then it registered properly and now shows as a switch
